packages:
  - frontend
  - backend
allowBuilds:
  '@parcel/watcher': set this to true or false
  esbuild: set this to true or false
  unrs-resolver: set this to true or false
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - unrs-resolver
